export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVITE_INVALID_OR_USED = 'INVITE_INVALID_OR_USED',
  INVITE_EXPIRED = 'INVITE_EXPIRED',
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',
  LEAVE_NOT_FOUND = 'LEAVE_NOT_FOUND',
  ATTENDANCE_NOT_FOUND = 'ATTENDANCE_NOT_FOUND',
  WX_BINDING_EXISTS = 'WX_BINDING_EXISTS',
}
